config/routes.rb
Rails.application.routes.draw do
  get 'queue' => 'queue#index'
  get 'queue/status' => 'queue#status', format: :json
  post 'queue/update' => 'queue#update'

  root to: 'dashboard#index'

  get 'login' => 'session#new', as: :login
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout

  post '/results' => 'results#record'
  get 'final_reports' => 'dashboard#final_reports'

  resources :rounds do
    member do
      get :standings
      get :scores
      get :kiosk
      get :self_scores
      get :edit_report, path: 'report'
      post :submit_report, path: 'report'
    end
  end

  resources :teams do
    collection do
      get :me, format: :json
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :basic_auth, only: %i(final_reports)

  def index
  end

  def final_reports
    reports = []

    FinalReport.all.includes(:team, :round).joins(:team, :round).each do |fr|
      bo = fr.benchmark_option
      bo.sub!(/\A((\.\/)?benchmarker)?( *bench)?/, '')
      bo = "--workload 1" if bo == "1"

      result = Result.by(fr.team).at(fr.round).latest.first
      sl = result.try(:submission_log)

      r = {
        id: fr.id,
        round_id: fr.round_id,
        round: fr.round.title,
        team_id: fr.team_id,
        team: fr.team.name,
        ami_id: fr.ami_id,
        language: fr.language,
        note: fr.note,
        benchmark_option: bo,
        benchmark_option_original: fr.benchmark_option
      }
      r[:result] =  {
        score: result.score,
        successes: result.successes,
        fails: result.fails
      } if result
      r[:meta] = JSON.parse(sl.meta) if sl

      reports << r
    end

    render json: reports
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |user, pass|
      user == 'isucon' && pass == 'on-memory'
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.slim
.rows
  .col-xs-6
    - if current_team
      h5 Your API Key
      pre
        code= session[:api_key]
    - else
      = link_to 'Login', login_path, class: 'btn btn-danger navbar-btn'

  .col-xs-6
    h5 Rounds
    .list-group
      - if current_team
        - rounds = (current_team.admin? ? Round.all : current_team.rounds)
      - else
        - rounds = Round.where(public: true)
      - rounds.each do |round|
        = link_to round_path(round), class: "list-group-item #{round.available? ? 'active' : ''}" do
          span.glyphicon.glyphicon-play
          == ' '
          = round.title