config/routes.rb
Rails.application.routes.draw do
  get 'queue' => 'queue#index'
  get 'queue/status' => 'queue#status', format: :json
  post 'queue/update' => 'queue#update'

  root to: 'dashboard#index'

  get 'login' => 'session#new', as: :login
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout

  post '/results' => 'results#record'
  get 'final_reports' => 'dashboard#final_reports'

  resources :rounds do
    member do
      get :standings
      get :scores
      get :kiosk
      get :self_scores
      get :edit_report, path: 'report'
      post :submit_report, path: 'report'
    end
  end

  resources :teams do
    collection do
      get :me, format: :json
    end
  end

end

app/models/round.rb
class Round < ActiveRecord::Base
  has_many :qualifications
  has_many :teams, through: :qualifications

  has_many :api_keys

  validates :starts_at, presence: true
  validates :ends_at, presence: true

  def teams_with_score
    @teams_with_score ||= begin
      team_ids = Result.at(self).group('results.team_id').pluck('results.team_id')
      Team.where(id: team_ids)
    end
  end

  def teams_with_highest_result
    teams.map do |team|
      [team, Result.by(team).at(self).highest]
    end
  end

  def teams_with_latest_result(time = Time.zone.now)
    teams.map do |team|
      [team, Result.by(team).at(self).in(self.starts_at .. time).latest.first]
    end
  end

  def available?(at = Time.zone.now)
    starts_at <= at && ends_at >= at
  end

  def report_deadline_exceed?
    report_deadline_at && report_deadline_at <= Time.zone.now
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :scores, :standings, :edit_report, :submit_report, :edit, :update, :destroy, :self_scores, :kiosk]
  before_action :require_viewer, only: [:show, :scores, :standings]
  before_action :require_participant, only: [:edit_report, :submit_report]
  before_action :require_admin, only: %i(new index create edit update destroy)

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  def kiosk
    render :kiosk, layout: nil
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def standings
    response_json = standings_array

    response_json.map! do |row|
      if row['team']['id'] == current_team.try(&:id)
        row['result'] = Result.by(current_team).at(@round).latest.first.as_json
      end
      row
    end
    response_json.sort_by! do |row|
      ((row['result'] || {})['score'] || 0) * -1
    end

    render json: response_json
  end

  def scores
    span = params[:span].to_i
    span = 1 if span < 1
    times = []
    team_scores = {}
    team_scores[current_team] = [] if current_team
    top_n = params[:top].to_i
    top_n = 5 if top_n < 5
    top_n = 10 if top_n > 10 && !current_team.try(&:admin?)

    cachekey = "scores-adm#{current_team.try(&:admin?) ? 1 : 0}n-#{span}-#{top_n}-#{@round.id}"
    team_scores = Rails.cache.fetch(cachekey, expires_in: 1.minute) do
      # Top N team
      top_n_team_ids = standings_array.reject { |team|
        team['team']['id'] == current_team.try(&:id)
      }.first(top_n).map { |team| team['team']['id'] }

      now = Time.zone.now
      Result.timesliced_score_for_round(@round, span.minutes) { |round, team, t|
        t <= now &&
        (
          current_team.try(&:admin?) ||
          t <= (@round.ends_at - 1.hour)
        )
      }.map do |team, scores|
        next if team[:id] != current_team.try(:id) && team[:name] != 'x' && !top_n_team_ids.include?(team[:id])
        [team[:name], *scores]
      end.compact.to_json
    end

    render json: team_scores
  end

  def self_scores
    unless current_team
      return render json: []
    end

    span = params[:span].to_i
    span = 1 if span < 1

    cachekey = "selfscores-adm#{current_team.id}-#{span}-#{@round.id}"
    team_scores = Rails.cache.fetch(cachekey, expires_in: 1.minute) do
      now = Time.zone.now
      Result.timesliced_score_for_round(@round, span.minutes, teams: [current_team.id]) { |round, team, t|
        t <= now
      }.map do |team, scores|
        [team[:name], *scores]
      end.compact.to_json
    end

    render json: team_scores
  end

  def edit_report
    unless @round.require_report?
      return render status: 404, text: "(\xE0\xB9\x91\xE2\x95\xB9\xE2\x97\xA1\xE2\x95\xB9\xE0\xB9\x91)"
    end

    @report = current_team.final_reports.for(@round).first || FinalReport.new
  end

  def submit_report
    unless @round.require_report?
      return render status: 404, text: "(\xE0\xB9\x91\xE2\x95\xB9\xE2\x97\xA1\xE2\x95\xB9\xE0\xB9\x91)"
    end

    @report = current_team.final_reports.for(@round).first || FinalReport.new
    if @report.new_record?
      @report.team = current_team
      @report.round = @round
    end
    @report.update(params.permit(:ami_id, :benchmark_option, :language, :note))
    @saved_report = @report.valid?

    render :edit_report
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_round
    @round = Round.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def round_params
    params.require(:round).permit(:title, :description, :starts_at, :ends_at, :public_description, :public, :require_report)
  end

  def require_participant
    unless current_team && (current_team.admin? || current_team.participate?(@round))
      redirect_to login_path
    end
  end

  def require_viewer
    unless @round.public? || (current_team && (current_team.admin? || current_team.participate?(@round)))
      redirect_to login_path
    end
  end

  def standings_array
    Rails.cache.fetch("round-#{current_team.try(&:admin?) ? 1 : 0}-standings-#{@round.id}", expires_in: 10.minutes) do
      time = Time.zone.now
      time = @round.ends_at - 1.hour if !current_team.try(&:admin?) && time > (@round.ends_at - 1.hour)

      @round.teams_with_latest_result(time).map { |team_with_latest|
        team = team_with_latest[0]
        result = team_with_latest[1]
        { team: team, result: result }
      }.sort_by { |obj|
        (obj[:result].try(:score) || 0) * -1
      }.as_json
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.slim
= form_for @round do |f|
  - if @round.errors.any?
    #error_explanation
      h2 = "#{pluralize(@round.errors.count, "error")} prohibited this round from being saved:"
      ul
        - @round.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :public_description
    = f.text_area :public_description
  .field
    = f.label :starts_at
    = f.datetime_field :starts_at
  .field
    = f.label :ends_at
    = f.datetime_field :ends_at

  .field
    = f.check_box :public
    = f.label :public
  .field
    = f.check_box :require_report
    = f.label :require_report

  .actions = f.submit 'Save'

app/views/rounds/_standings.html.slim
- if true
- else
  p standings were masked...

app/views/rounds/edit.html.slim
h1 Editing round

== render 'form'

= link_to 'Show', @round
'|
= link_to 'Back', rounds_path

app/views/rounds/edit_report.html.slim
.rows
  .col-xs-8.col-xs-offset-2
    h1.page-header.text-center AMI ID 情報の提出

    - if @report.errors.any?
      .alert.alert-danger
        - @report.errors.full_messages.each do |message|
          p= message

    - if @saved_report
      .alert.alert-info
        p AMI ID 情報を提出しました。

    - if @round.report_deadline_exceed?
      .alert.alert-danger
        - if @report.try(&:persisted?)
          p 提出期限を過ぎているので、提出済み情報の編集はできません。
        - else
          p 提出期限を過ぎているので、提出はできません。

    = form_tag edit_report_round_path(@round.id), { class: 'form-horizontal' } do
      - if @round.report_deadline_at
        .form-group
          label.control-label.col-xs-4 提出期限
          .col-xs-8
            p.form-control-static= l @round.report_deadline_at

      .form-group
        label.control-label.col-xs-4 チーム名
        .col-xs-8
          p.form-control-static= current_team.name
      .form-group
        label.control-label.col-xs-4 AMI ID
        .col-xs-8
          = text_field_tag :ami_id, @report.ami_id, class: 'form-control', pattern: '^ami-[0-9a-fA-F]+$', placeholder: 'ami-xxxxxxxx'
          span.help-text
            strong.text-danger この AMI ID は必ず AWS ID: 983977107217 に共有してください。
      .form-group
        label.control-label.col-xs-4 ベンチマーカーの起動オプション
        .col-xs-8
          = text_field_tag :benchmark_option, @report.benchmark_option, class: 'form-control', placeholder: '--workload N'
          span.help-text
            | API Key を含まない、最終スコア送信時の起動オプションを入力してください。
      .form-group
        label.control-label.col-xs-4 利用した言語
        .col-xs-8
          = text_field_tag :language, @report.language, class: 'form-control', placeholder: 'Ruby'
      .form-group
        label.control-label.col-xs-4 その他備考・メモ
        .col-xs-8
          = text_area_tag :note, @report.note, class: 'form-control', rows: 5

      - unless @round.report_deadline_exceed?
        .form-group
          .col-xs-8.col-xs-offset-2
            = submit_tag @report.new_record? ? '送信' : '修正', class: 'btn btn-block btn-lg btn-primary'

app/views/rounds/index.html.slim
h1 Listing rounds

table
  thead
    tr
      th Title
      th Description
      th
      th
      th

  tbody
    - @rounds.each do |round|
      tr
        td = round.title
        td = round.description
        td = link_to 'Show', round
        td = link_to 'Edit', edit_round_path(round)
        td = link_to 'Destroy', round, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Round', new_round_path

app/views/rounds/kiosk.html.slim
doctype html
html(class="#{controller_path.gsub('/', '-')}-controller #{action_name}-action")
  head
    meta(charset='utf-8')
    meta(name='viewport' content='width=device-width, initial-scale=1.0')
    title= content_for?(:title) ? yield(:title) : 'ISUCON4 Portal site'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    .container-fluid
      .round-description(style="display: none;" data-endpoint=url_for(@round))

      - if (@round.starts_at <= Time.zone.now || current_team.try(&:admin?))
        #round-ended.panel.panel-default(data-show-on=@round.ends_at style="display:none;")
          .panel-heading #{@round.title} は終了しました
          .panel-body
            p お疲れさまでした!

        #score-graph
          .clearfix
            .btn-toolbar.pull-right
              .btn-group
                .btn.btn-default(v-class='active: topN == 5' v-on='click: setTopN(5)') Top 5
                .btn.btn-default(v-class='active: topN == 10' v-on='click: setTopN(10)') Top 10
                - if current_team.try(:admin?)
                  .btn.btn-default(v-class='active: topN == 100' v-on='click: setTopN(100)') ALL
              .btn-group
                .btn.btn-default(v-class='active: graphSpan == 1' v-on='click: setGraphSpan(1)') 1 min
                .btn.btn-default(v-class='active: graphSpan == 5' v-on='click: setGraphSpan(5)') 5 min
                .btn.btn-default(v-class='active: graphSpan == 10' v-on='click: setGraphSpan(10)') 10 min
              .btn-group
                .btn.btn-primary(v-on='click: reloadNow' v-class='active: loadingNow')
                  span.glyphicon.glyphicon-refresh(v-class='spin: loadingNow')
              - if current_team.try(:admin?)
                .btn-group
                  .btn.btn-default(v-on='click: fullscreenGraph')
                    span.glyphicon.glyphicon-fullscreen

          #score-chart(v-pre)

        table.table.table-striped#standings
          thead
            tr
              th.text-right #
              th Team
              th Score
              th.text-right At
          tbody
            tr.hide(v-class='hide: false' v-repeat="team : teams")
              td.ranking-cell
                span.label(v-class='label-success: $index < 5' v-text='$index+1')
              td.team-cell(v-text='team.name')
              td
                strong(v-text='team.score')
              td.text-right(v-text='team.at | relativeTime')
      - else
        .alert.alert-info
          p #{@round.title}の開始予定時刻は #{@round.starts_at.strftime('%Y-%m-%d %H:%M:%S')} を予定しています。
          p 開始までお待ち下さい。

app/views/rounds/new.html.slim
h1 New round

== render 'form'

= link_to 'Back', rounds_path

app/views/rounds/show.html.slim
h1.page-header= @round.title

- if (@round.starts_at <= Time.zone.now || current_team.try(&:admin?))
  - if @round.require_report?
    #round-ended.modal.fade(data-show-on=@round.ends_at)
      .modal-dialog
        .modal-content
          .modal-header
            button.close(data-dismiss="modal") &times;
            h4.modal-title #{@round.title}は終了しました。
          .modal-body
            p #{@round.title}は終了しました。AMI ID 等の最終情報を未提出の方は、必ず提出してください。
          .modal-footer
            = link_to edit_report_round_path(@round.id), class: 'btn btn-lg btn-primary' do
              == 'AMI ID 情報を提出 '
              span.glyphicon.glyphicon-chevron-right
  - else
    #round-ended.panel.panel-default(data-show-on=@round.ends_at style="display:none;")
      .panel-heading #{@round.title} は終了しました
      .panel-body
        p お疲れさまでした!

  section.round-description(data-endpoint=url_for(@round))
    - if current_team && (current_team.admin? || current_team.participate?(@round))
      = markdown @round.description
    = markdown @round.public_description

  h3 Score graph

  .text-muted
    p あなたのチームと、上位5チーム(もしくは10チーム)のスコアをグラフで表示しています。
    p あなたのチーム以外のグラフの更新は、終了1時間前に停止します。

  #score-graph
    .clearfix
      .btn-toolbar.pull-right
        .btn-group
          .btn.btn-default(v-class='active: topN == 5' v-on='click: setTopN(5)') Top 5
          .btn.btn-default(v-class='active: topN == 10' v-on='click: setTopN(10)') Top 10
          - if current_team.try(:admin?)
            .btn.btn-default(v-class='active: topN == 100' v-on='click: setTopN(100)') ALL
        .btn-group
          .btn.btn-default(v-class='active: graphSpan == 1' v-on='click: setGraphSpan(1)') 1 min
          .btn.btn-default(v-class='active: graphSpan == 5' v-on='click: setGraphSpan(5)') 5 min
          .btn.btn-default(v-class='active: graphSpan == 10' v-on='click: setGraphSpan(10)') 10 min
        .btn-group
          .btn.btn-primary(v-on='click: reloadNow' v-class='active: loadingNow')
            span.glyphicon.glyphicon-refresh(v-class='spin: loadingNow')
        - if current_team.try(:admin?)
          .btn-group
            .btn.btn-default(v-on='click: fullscreenGraph')
              span.glyphicon.glyphicon-fullscreen

    #score-chart(v-pre)


  h3 Standings

  p.text-muted
    | 順位の更新は、終了1時間前に停止します。

  table.table.table-striped
    thead
      tr
        th.text-right #
        th Team
        th Score
        th.text-right At
    tbody
      tr.hide(v-class='hide: false' v-repeat="team : teams")
        td.ranking-cell
          span.label(v-class='label-success: $index < 5' v-text='$index+1')
        td.team-cell(v-text='team.name')
        td
          strong(v-text='team.score')
        td.text-right(v-text='team.at | relativeTime')
- else
  .alert.alert-info
    p #{@round.title}の開始予定時刻は #{@round.starts_at.strftime('%Y-%m-%d %H:%M:%S')} を予定しています。
    p 開始までお待ち下さい。