config/routes.rb
Rails.application.routes.draw do
  get 'queue' => 'queue#index'
  get 'queue/status' => 'queue#status', format: :json
  post 'queue/update' => 'queue#update'

  root to: 'dashboard#index'

  get 'login' => 'session#new', as: :login
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout

  post '/results' => 'results#record'
  get 'final_reports' => 'dashboard#final_reports'

  resources :rounds do
    member do
      get :standings
      get :scores
      get :kiosk
      get :self_scores
      get :edit_report, path: 'report'
      post :submit_report, path: 'report'
    end
  end

  resources :teams do
    collection do
      get :me, format: :json
    end
  end

end

app/views/layouts/application.html.slim
doctype html
html(class="#{controller_path.gsub('/', '-')}-controller #{action_name}-action")
  head
    meta(charset='utf-8')
    meta(name='viewport' content='width=device-width, initial-scale=1.0')
    title= content_for?(:title) ? yield(:title) : 'ISUCON4 Portal site'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          = link_to root_path, class: 'navbar-brand' do
            span.text-danger ISUCON4
            == ' Portal Site'

        .collapse.navbar-collapse
          .navbar-left
            - if current_team
              p.navbar-text= current_team.name

          .navbar-right
            - if current_team
              = link_to 'Logout', logout_path, method: :delete, class: 'btn btn-danger navbar-btn'
            - else
              = link_to 'Login', login_path, class: 'btn btn-danger navbar-btn'

    .container
      = yield